from __future__ import annotations
from abc import ABC, abstractmethod
import json
import logging
import typing
import httpx
from langchain.chat_models import init_chat_model
from langchain_core.messages import AIMessageChunk
from langchain_core.messages.base import TextAccessor

logger = logging.getLogger()


class AbstractAiclient(ABC):
    @abstractmethod
    def get_response(self, input_text: str | None) -> typing.AsyncGenerator[str]:
        """Takes in LLM input query, returns LLM response"""
        raise NotImplementedError

    async def response_generator(self, text: str = "") -> typing.AsyncGenerator[str]:
        """
        Generator that aggregates small AI token chunks into sentence/phrase chunks so the frontend
        receives meaningful text quickly (a sentence or two at a time) instead of many tiny pieces.
        """

        async for chunk in self.get_response(text):
            if type(chunk) is AIMessageChunk:
                yield chunk.text


class DebugAiClient(AbstractAiclient):
    async def get_response(self, input_text: str) -> typing.AsyncGenerator[str] | str:
        """
        Returns hardcoded response, without contacting any external api,
        by streaming them character by character.
        parameters:
            input_text: input to debug AI client
        yields:
            AsyncGenerator[str]: response streamed character by character
        """
        static_mapping = {
            "hi": "Hello Chatter!",
            "hello": "Hello Chatter!",
            "good morning": "Hello Chatter",
            "what is the weather?": "If it's a day, it's probably sunny with some clouds. "
            "if it's a night, then it likely moony, assuming there are no clouds covering moon.",
            "bye": "Good bye!",
            "debug": "Lorem ipsum sit doloret ames.",
        }
        if not input_text or input_text.lower() not in static_mapping.keys():
            data = """Welcome to the chat! This response is currently hardcoded, but will be generated by LLM in the future :)"""
        else:
            data = static_mapping.get(input_text.lower(), "")

        for char in data:
            yield char


class OllamaAiClient(AbstractAiclient):
    async def get_response(self, input_text: str | None) -> typing.AsyncGenerator[str]:
        """Streams response character by character from Ollama LLM server
        parameters:
            input_text: input to Ollama LLM
        yields:
            AsyncGenerator[str]: response streamed from ollama character by character
        """
        from config.settings import Config

        logger.warning(
            "LangchainOllamaClient is deprecated, use LangchainOllamaClient rewrite utilizing langchain instead"
        )
        ollama_url = Config.OLLAMA_URL
        ollama_model = Config.OLLAMA_MODEL
        client = httpx.AsyncClient()
        async with client.stream(
            "POST",
            ollama_url,
            json={
                "model": ollama_model,
                "messages": [
                    {"role": "system", "content": Config.OLLAMA_SYSTEM_PROMPT},
                    {"role": "user", "content": input_text},
                ],
            },
            timeout=30,
        ) as response:
            async for line in response.aiter_lines():
                if not line:
                    continue
                json_chunk = json.loads(line)

                content = json_chunk["message"]["content"]
                done = json_chunk["done"]
                if done is False:
                    yield content


class LangchainOllamaClient(AbstractAiclient):
    def __init__(self):
        from config.settings import Config

        self.client = init_chat_model(
            base_url=Config.OLLAMA_ROOT_URL,
            model_provider=Config.MODEL_PROVIDER,
            model=Config.OLLAMA_MODEL,
        )
        self.base_config = Config

    async def get_response(
        self, input_text: str | None
    ) -> typing.AsyncGenerator[TextAccessor]:
        messages = [
            {"role": "system", "content": self.base_config.OLLAMA_SYSTEM_PROMPT},
            {"role": "user", "content": input_text},
        ]
        async for chunk in self.client.astream(messages):
            yield chunk.text


class AIServiceManager:
    ai_services = {
        "debug": DebugAiClient,
        "ollama": OllamaAiClient,
        "langchain-ollama": LangchainOllamaClient,
    }

    @classmethod
    def get_service(cls, ai_client_type) -> AbstractAiclient:
        """
        Retrieve AI Service handling ai interaction that is configured in settings,
        such as Langchain ollama, debug client, etc.
        """
        service = cls.ai_services.get(ai_client_type, DebugAiClient)
        logging.info(f"Using AI client: {service.__name__}")
        return service()
