from __future__ import annotations

import json
import logging
import typing
from abc import ABC, abstractmethod
from typing import Any

import httpx
from langchain.agents import create_agent
from langchain.chat_models import init_chat_model
from langchain_core.messages import AIMessageChunk, HumanMessage
from langchain_core.stores import InMemoryBaseStore, InMemoryStore
from langgraph.checkpoint.memory import InMemorySaver
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from langgraph.types import Checkpointer
    from langchain_core.runnables import RunnableConfig
    from config.settings import Config


logger = logging.getLogger()


class AbstractAiclient(ABC):
    def __init__(self, config: Config):
        self.config: Config = config

    async def get_response(self, *args, **kwargs) -> typing.AsyncGenerator[str]:
        """
        Wrapper around _get_response generator, for error handling and other behaviour
        before and after querying model and getting response.
        """
        try:
            async for chunk in self._get_response(*args, **kwargs):
                yield chunk
        except Exception:
            logger.exception(
                "There was an error while trying to generate response to user query: %s",
            )
            yield (
                "It seems there was some issue handling your question. "
                "Please try again."
            )
            raise

    @abstractmethod
    def _get_response(self, input_text: str | None) -> typing.AsyncGenerator[str]:
        """Take in LLM input query and return LLM response."""
        raise NotImplementedError


class DebugAiClient(AbstractAiclient):
    async def _get_response(self, input_text: str | None) -> typing.AsyncGenerator[str]:
        """
        Return hardcoded response, without contacting any external api
        by streaming them character by character.

        Parameters
        ----------
            input_text: input to debug AI client
        yields:
            AsyncGenerator[str]: response streamed character by character

        """
        static_mapping = {
            "hi": "Hello Chatter!",
            "hello": "Hello Chatter!",
            "good morning": "Hello Chatter",
            "what is the weather?": "If it's a day, "
            "it's probably sunny with some clouds. "
            "if it's a night, then it likely moony, "
            "assuming there are no clouds covering moon.",
            "bye": "Good bye!",
            "debug": "Lorem ipsum sit doloret ames.",
        }
        if not input_text or input_text.lower() not in static_mapping:
            data = """Welcome to the chat! This response is currently hardcoded,
            but will be generated by LLM in the future :)"""
        else:
            data = static_mapping.get(input_text.lower(), "")

        for char in data:
            yield char


class OllamaAiClient(AbstractAiclient):
    async def _get_response(self, input_text: str | None) -> typing.AsyncGenerator[str]:
        """Stream response character by character from Ollama LLM server.

        Parameters
            input_text: input to Ollama LLM.
        yields:
            AsyncGenerator[str]: response streamed from ollama character by character.
        """
        logger.warning(
            "OllamaAiClient is deprecated, ",
            "use LangchainOllamaClient rewrite utilizing langchain instead",
        )
        ollama_url = self.config.OLLAMA_URL
        ollama_model = self.config.OLLAMA_MODEL
        client = httpx.AsyncClient()
        async with client.stream(
            "POST",
            ollama_url,
            json={
                "model": ollama_model,
                "messages": [
                    {"role": "system", "content": self.config.OLLAMA_SYSTEM_PROMPT},
                    {"role": "user", "content": input_text},
                ],
            },
            timeout=30,
        ) as response:
            async for line in response.aiter_lines():
                if not line:
                    continue
                json_chunk = json.loads(line)

                content = json_chunk["message"]["content"]
                done = json_chunk["done"]
                if done is False:
                    yield content


class LangchainOllamaClient(AbstractAiclient):
    def __init__(self, config: Config) -> None:
        super().__init__(config)
        self.checkpointer, self.store = self._set_up_memory()
        self.model = init_chat_model(
            base_url=self.config.OLLAMA_ROOT_URL,
            model_provider=self.config.MODEL_PROVIDER,
            model=self.config.OLLAMA_MODEL,
        )
        self.client = create_agent(
            model=self.model,
            system_prompt=self.config.OLLAMA_SYSTEM_PROMPT,
            checkpointer=self.checkpointer,
        )

    def _set_up_memory(self) -> tuple[Checkpointer, InMemoryBaseStore]:
        return InMemorySaver(), InMemoryStore()

    async def _get_response(self, input_text: str | None) -> typing.AsyncGenerator[str]:
        """
        Send request to the model,
        generate response that is saved in memory and streamed back.
        """
        messages: dict[str, list[HumanMessage]] = {
            "messages": [HumanMessage(content=input_text)],
        }
        conversation_config: RunnableConfig = {"configurable": {"thread_id": 1}}
        chunks: list[tuple[AIMessageChunk, dict[str, Any]]] = []
        full_text_response = ""

        async for chunk in self.client.astream(  # type: ignore
            input=messages,  # type: ignore
            config=conversation_config,
            stream_mode="messages",
        ):
            chunk: tuple[AIMessageChunk, dict[str, Any]]
            message_chunk = chunk[0]  # chunk[0] is ai res object, chunk[1] is metadata
            if isinstance(message_chunk, AIMessageChunk):
                text = message_chunk.text
                # TODO: pack AI generated output into schema
                yield text
                chunks.append((message_chunk, {}))
                full_text_response += text

        if self.config.DEBUG:
            logger.info("User input to model: %s", input_text)
            logger.info("Final streamed output: %s", full_text_response)
            logger.info("%s chunks were returned.", len(chunks))


class AIServiceManager:
    """Create, cache and return AI service."""

    ai_services: typing.ClassVar = {
        "debug": DebugAiClient,
        "ollama": OllamaAiClient,
        "langchain-ollama": LangchainOllamaClient,
    }
    _instances: typing.ClassVar[dict[str, AbstractAiclient]] = {}

    @classmethod
    def get_service(
        cls,
        ai_client_type: str,
        config: Config,
    ) -> AbstractAiclient:
        """Get and return AI service.

        Create and store instance of AI service
        between requests depending on configuration in settings.
        """
        service_cls = cls.ai_services.get(ai_client_type, DebugAiClient)
        cached_service = cls._instances.get(ai_client_type)

        if cached_service is None:
            logger.info("Using AI client: %s", service_cls.__name__)
            cached_service = service_cls(config)
            cls._instances[ai_client_type] = cached_service
        else:
            logger.info(
                "Using existing instance of AI client: %s",
                service_cls.__name__,
            )
            cached_service.config = config
        return cached_service
